basePath: /api/v1
definitions:
  models.Conversion:
    properties:
      conversion_from:
        type: integer
      conversion_to:
        type: integer
      rate:
        type: integer
    type: object
  models.Currency:
    properties:
      name:
        type: string
    type: object
info:
  contact:
    email: reziapriliansyah@gmail.com
    name: Rezi Apriliansyah
  description: API documentation for Game Currency
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Game Currency
  version: 1.0.0
paths:
  /conversion:
    post:
      description: Create a new conversion
      operationId: create-conversion
      parameters:
      - description: Create conversion
        in: body
        name: player
        required: true
        schema:
          $ref: '#/definitions/models.Conversion'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Conversion'
      summary: Create a new conversion
      tags:
      - conversion
  /convert:
    post:
      description: Create convert rate
      operationId: convert-conversion
      parameters:
      - default: 1
        description: conversion id from
        in: query
        name: from
        required: true
        type: integer
      - default: 1
        description: conversion id to
        in: query
        name: to
        required: true
        type: integer
      - default: 1
        description: amount
        in: query
        name: amount
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            type: object
      summary: Create convert rate
      tags:
      - conversion
  /currency:
    get:
      description: Get the list of currency
      operationId: list-currency
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Currency'
            type: array
      summary: List currency
      tags:
      - currency
    post:
      description: Create a new currency
      operationId: create-currency
      parameters:
      - description: Create currency
        in: body
        name: player
        required: true
        schema:
          $ref: '#/definitions/models.Currency'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Currency'
      summary: Create a new currency
      tags:
      - currency
swagger: "2.0"
